config/routes.rb
Rails.application.routes.draw do
  get 'page/home'
  devise_for :users
  root "posts#index", as: "home"

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence: true
  validates :body, presence: true, length: {minimum:1,maximum:200}
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :title, presence: true, length: {minimum:1, maximum:50}
    validates :body, presence: true, length: {minimum:1, maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        @comment.times = DateTime.current
        @comment.username = current_user.email
        @comment.save
        redirect_to posts_path(@post)
    end
    private def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def contacts
        @contacts = Array['<a href="vk.com/sherlok6"> << ВК >> </a>', 
            '<a href="instagram/snd_zero"> << Instagram >> </a>']
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    def new
        @post = Post.new
    end
    def create
        @post = Post.new(post_params)
        @post.dt_post = DateTime.current
        @post.user = current_user
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    private def post_params
        params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <h1 class="fs-4 font-weight-bold">Мой блог</h1>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <span class="me-3 py-2 text-dark text-decoration-none" >
          <%= link_to "Главная страница", home_path %>
        </span>
        <% if current_user %>
          <span class="me-3 py-2 text-dark text-decoration-none" >
            <%= link_to current_user.email, page_home_path %>
          </span>
          <span class="me-3 py-2 text-dark text-decoration-none" >
            <%= link_to "Новый пост", new_post_path %>
          </span>
        <% else %>
          <span class="me-3 py-2 text-dark text-decoration-none" >
              <%= link_to "Войти в профиль", new_user_session_path %>
            </span>
            <span class="me-3 py-2 text-dark text-decoration-none" >
              <%= link_to "Зарегистрироваться", new_user_registration_path %>
            </span>
        <% end %>
      </nav>
    </div>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/page/home.html.erb
<h1>Профиль пользователя <%= current_user.email %></h1>
<% if current_user.posts == nil%>
    <h2>У вас нет постов</h2>
<% else %>
    <% (current_user.posts).each do |post|%>
        <div>
            <h3><%= post.title %></h3>
            <%= link_to "Прочитать пост", post_path(post) %>
        </div>
    <% end %>
<% end %>
<div>
    <%= link_to "Выйти из профиля", destroy_user_session_path, method: :delete %>
</div>

app/views/pages/contacts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
  </head>

  <body>
    <h2>Контакты</h2>
    <p><%= @contacts[0] %></p>

    <p><%= @contacts[1] %></p>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Изменение поста</h1>
<%= form_for :post, url:post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <%= msg %>
    <% end %>
  <% end %>
<p>
        Заголовок: <%= f.text_field(:title) %></p>
    <p>
        Текст поста: <%= f.text_area(:body) %></p>
    <p><%= f.submit %></p>
<% end %>

app/views/posts/index.html.erb
<h1>Все посты</h1>
<% @posts.each do |post|%>
    <div class="container">
        <p><%= post.title %></p>
        <p><%= post.dt_post %></p>
        <%= link_to "Прочитать пост", post_path(post) %>
        <br>
        <strong>Автор: <%= post.user.email %></strong>
    </div>
    <br>
<% end %>

app/views/posts/new.html.erb
<h1>Добавить пост</h1>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <%= msg %>
        <br>
    <% end %>
  <% end %>
<%= form_for :post, url:posts_path do |f| %>
    <p>
        Заголовок: <%= f.text_field(:title,{:class => 'form-control'}) %></p>
    <p>
        Текст поста: <%= f.text_area(:body,{:class => 'form-control'}) %></p>
    <p><%= f.submit("Добавить пост",{:class => 'btn btn-success'} ) %></p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<br>
<strong><%= @post.dt_post %></strong>
<br>
<% if current_user == @post.user %>
  <strong><%= link_to "Редактировать пост", edit_post_path(@post) %></strong>
  <strong><%= link_to "Удалить пост", post_path(@post), method: :delete,
    data: { confirm: 'Вы хотите удалить пост?' } %></strong>
<% end %>
<br>
<% if current_user %>
  <% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |msg| %>
        <%= msg %>
        <br>
    <% end %>
  <% end %>
    <h2>Добавить комментарии</h2>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        Комментарий <br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit("Добавить комментарий") %>
    </p>
  <% end %>
<% else %>
  <%= link_to "Войдите в профиль", new_user_session_path %> <span> или </span> <%= link_to "Зарегистрироваться", new_user_registration_path %>
<% end %>

<% if (@post.comments).length()-1 == 0 %>
  <h3>К этому посту нет комментарией</h3>
<% else %>
<h2>Все комментарии к посту</h2>
  <% @post.comments.each do |comment| %>
    <div>
      <p><%= comment.username %> :: <%= comment.body%></p>
      <strong><%= comment.times %></strong>
    </div>
  <% end %>
<% end %>  